# ============================================
# Configuración para Kubernetes
# ============================================

spring:
  config:
    activate:
      on-profile: k8s
  
  # Las variables vendrán de ConfigMaps y Secrets
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:10}
      minimum-idle: ${DB_MIN_IDLE:2}
  
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD:}
  
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

# Configuración para Kubernetes
innosistemas:
  auth:
    jwt:
      secret: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION:86400}
      refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800}
  
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}